export const MAX_AMOUNT = 999_999.99;

export const COLORS = {
  primary: '#2563EB',
  income: '#16A34A',
  expense: '#DC2626',
  background: '#F9FAFB',
  card: '#FFFFFF',
} as const;

export const RECORD_CATEGORIES = {
  expense: [
    {
      id: 'life',
      name: '生活',
      icon: '🏠',
      children: [
        { id: 'life-daily', name: '日用品', icon: '🧻' },
        { id: 'life-utility', name: '水电燃气', icon: '💡' },
        { id: 'life-phone', name: '通讯网费', icon: '📱' },
        { id: 'life-service', name: '家政维修', icon: '🧰' },
        { id: 'life-pet', name: '宠物花费', icon: '🐾' },
        { id: 'life-other', name: '生活杂项', icon: '🧺' },
      ],
    },
    {
      id: 'food-traffic',
      name: '餐饮交通',
      icon: '🍜',
      children: [
        { id: 'food-breakfast', name: '早餐', icon: '🥟' },
        { id: 'food-lunch', name: '午餐', icon: '🍱' },
        { id: 'food-dinner', name: '晚餐', icon: '🍲' },
        { id: 'food-coffee', name: '奶茶咖啡', icon: '☕' },
        { id: 'traffic-public', name: '公交地铁', icon: '🚇' },
        { id: 'traffic-taxi', name: '打车', icon: '🚕' },
        { id: 'traffic-car', name: '油费停车', icon: '⛽' },
      ],
    },
    {
      id: 'shopping',
      name: '购物',
      icon: '🛒',
      children: [
        { id: 'shopping-clothes', name: '服饰鞋包', icon: '👕' },
        { id: 'shopping-digital', name: '数码电器', icon: '🎧' },
        { id: 'shopping-beauty', name: '美妆护理', icon: '🧴' },
        { id: 'shopping-home', name: '家居百货', icon: '🛋️' },
        { id: 'shopping-online', name: '网购', icon: '📦' },
      ],
    },
    {
      id: 'social',
      name: '人情世故',
      icon: '🧧',
      children: [
        { id: 'social-wedding', name: '婚礼随份子', icon: '💐' },
        { id: 'social-baby', name: '满月百日', icon: '🍼' },
        { id: 'social-festival', name: '节日红包', icon: '🧧' },
        { id: 'social-gift', name: '送礼', icon: '🎁' },
        { id: 'social-treat', name: '请客吃饭', icon: '🍻' },
        { id: 'social-visit', name: '探望慰问', icon: '🍎' },
      ],
    },
    {
      id: 'large',
      name: '大额支出',
      icon: '💰',
      children: [
        { id: 'large-appliance', name: '家电大件', icon: '📵' },
        { id: 'large-renovation', name: '装修家具', icon: '🛜' },
        { id: 'large-travel', name: '旅行度假', icon: '✈️' },
        { id: 'large-car', name: '车辆相关', icon: '🚫' },
        { id: 'large-medical', name: '大额医疗', icon: '🏞' },
        { id: 'large-emergency', name: '应急支出', icon: '🆘' },
      ],
    },
    {
      id: 'housing',
      name: '居住账单',
      icon: '🏠',
      children: [
        { id: 'housing-rent', name: '房租', icon: '🔑' },
        { id: 'housing-loan', name: '房贷', icon: '🏟' },
        { id: 'housing-property', name: '物业费', icon: '🏚' },
        { id: 'housing-internet', name: '宽带电视', icon: '📗' },
      ],
    },
    {
      id: 'health-education',
      name: '医疗教育',
      icon: '📎',
      children: [
        { id: 'health-medicine', name: '买药', icon: '🏪' },
        { id: 'health-clinic', name: '看病检查', icon: '🏠' },
        { id: 'education-course', name: '课程培训', icon: '🏗' },
        { id: 'education-book', name: '书籍资料', icon: '📉' },
      ],
    },
    {
      id: 'entertainment',
      name: '娱乐休闲',
      children: [
        { id: 'ent-movie', name: '电影演出', icon: '🎬' },
        { id: 'ent-game', name: '游戏充值', icon: '🎮' },
        { id: 'ent-karaoke', name: 'K歌桌游', icon: '🎤' },
        { id: 'ent-sport', name: '运动健身', icon: '🏋️' },
        { id: 'ent-travel', name: '周边游玩', icon: '🏕️' },
        { id: 'ent-hobby', name: '兴趣爱好', icon: '🎨' },
      ],
    },
    {
      id: 'children',
      name: '子女育儿',
      children: [
        { id: 'child-milk', name: '奶粉辅食', icon: '🍼' },
        { id: 'child-diaper', name: '尿不湿用品', icon: '🩲' },
        { id: 'child-toy', name: '玩具绘本', icon: '🧸' },
        { id: 'child-edu', name: '早教培训', icon: '📚' },
        { id: 'child-clothes', name: '童装鞋帽', icon: '👕' },
        { id: 'child-med', name: '儿科医疗', icon: '🏥' },
      ],
    },
    {
      id: 'other-expense',
      name: '其他',
      icon: '💸',
      children: [
        { id: 'other-temp', name: '临时支出', icon: '📑' },
        { id: 'other-unknown', name: '未分类', icon: '❓' },
      ],
    },
  ],
  income: [
    {
      id: 'salary',
      name: '工资',
      icon: '💈',
      children: [
        { id: 'salary-base', name: '固定工资', icon: '💈' },
        { id: 'salary-bonus', name: '奖金绩效', icon: '🏲' },
        { id: 'salary-subsidy', name: '补贴报销', icon: '🜘' },
      ],
    },
    {
      id: 'entertainment',
      name: '娱乐休闲'
      icon: '💳',
      children: [
        { id: 'large-appliance', name: '家电大件', icon: '📺' },
        { id: 'large-renovation', name: '装修家具', icon: '🛠️' },
        { id: 'large-travel', name: '旅行度假', icon: '✈️' },
        { id: 'large-car', name: '车辆相关', icon: '🚗' },
        { id: 'large-medical', name: '大额医疗', icon: '🏥' },
        { id: 'large-emergency', name: '应急支出', icon: '🧯' },
      ],
    },
    {
      id: 'housing',
      name: '居住账单',
      icon: '🏡',
      children: [
        { id: 'housing-rent', name: '房租', icon: '🔑' },
        { id: 'housing-loan', name: '房贷', icon: '🏦' },
        { id: 'housing-property', name: '物业费', icon: '🏢' },
        { id: 'housing-internet', name: '宽带电视', icon: '📡' },
      ],
    },
    {
      id: 'health-education',
      name: '医疗教育',
      icon: '📚',
      children: [
        { id: 'health-medicine', name: '买药', icon: '💊' },
        { id: 'health-clinic', name: '看病检查', icon: '🩺' },
        { id: 'education-course', name: '课程培训', icon: '🎓' },
        { id: 'education-book', name: '书籍资料', icon: '📖' },
      ],
    },
    {
      id: 'other-expense',
      name: '其他',
      icon: '💸',
      children: [
        { id: 'other-temp', name: '临时支出', icon: '📝' },
        { id: 'other-unknown', name: '未分类', icon: '❓' },
      ],
    },
  ],
  income: [
    {
      id: 'salary',
      name: '工资',
      icon: '💼',
      children: [
        { id: 'salary-base', name: '固定工资', icon: '💼' },
        { id: 'salary-bonus', name: '奖金绩效', icon: '🏅' },
        { id: 'salary-subsidy', name: '补贴报销', icon: '🧾' },
      ],
    },
    {
      id: 'part-time',
      name: '兼职',
      icon: '🧾',
      children: [
        { id: 'part-time-job', name: '兼职收入', icon: '🧑‍💻' },
        { id: 'part-time-project', name: '项目收入', icon: '📁' },
        { id: 'part-time-service', name: '服务酬劳', icon: '🤝' },
      ],
    },
    {
      id: 'gift-income',
      name: '红包礼金',
      icon: '🧧',
      children: [
        { id: 'gift-redpacket', name: '红包', icon: '🧧' },
        { id: 'gift-money', name: '礼金', icon: '🎁' },
        { id: 'gift-family', name: '家人转账', icon: '👪' },
      ],
    },
    {
      id: 'finance',
      name: '理财',
      icon: '📈',
      children: [
        { id: 'finance-interest', name: '利息', icon: '🏦' },
        { id: 'finance-investment', name: '投资收益', icon: '📈' },
        { id: 'finance-refund', name: '退款返现', icon: '↩️' },
      ],
    },
    {
      id: 'other-income',
      name: '其他',
      icon: '💰',
      children: [
        { id: 'other-income-temp', name: '临时收入', icon: '💰' },
        { id: 'other-income-unknown', name: '未分类', icon: '❓' },
      ],
    },
  ],
} as const;

export const QUICK_NOTES = {
  'life-daily': ['买了纸巾', '洗衣液', '厨房用品', '生活耗材'],
  'life-utility': ['交电费', '交水费', '燃气费', '取暖费'],
  'life-phone': ['手机话费', '宽带续费', '流量包'],
  'life-service': ['修水管', '换灯具', '家政保洁', '开锁维修'],
  'life-pet': ['宠物粮', '宠物医院', '宠物洗护'],
  'life-other': ['生活杂项', '临时采购'],
  'food-breakfast': ['早餐', '包子豆浆', '便利店早餐'],
  'food-lunch': ['午餐', '工作餐', '外卖午餐'],
  'food-dinner': ['晚餐', '聚餐晚饭', '外卖晚餐'],
  'food-coffee': ['奶茶', '咖啡', '甜品'],
  'traffic-public': ['地铁', '公交', '通勤交通'],
  'traffic-taxi': ['打车', '网约车', '机场车费'],
  'traffic-car': ['加油', '停车费', '洗车', '高速费'],
  'shopping-clothes': ['买了衣服', '买鞋', '买包'],
  'shopping-digital': ['买耳机', '买手机配件', '买电脑配件'],
  'shopping-beauty': ['护肤品', '洗护用品', '理发'],
  'shopping-home': ['家居用品', '收纳用品', '床品'],
  'shopping-online': ['网购', '快递到付', '平台会员'],
  'social-wedding': ['随份子', '婚礼礼金', '伴手礼'],
  'social-baby': ['满月酒', '百日宴', '宝宝红包'],
  'social-festival': ['过年红包', '节日礼金', '长辈红包'],
  'social-gift': ['送礼', '生日礼物', '伴手礼'],
  'social-treat': ['请客吃饭', '朋友聚餐', '客户招待'],
  'social-visit': ['探望病人', '慰问长辈', '水果礼盒'],
  'large-appliance': ['买冰箱', '买电视', '买洗衣机', '买空调'],
  'large-renovation': ['装修支出', '买家具', '材料费'],
  'large-travel': ['机票酒店', '旅行团费', '景点门票'],
  'large-car': ['保险保养', '维修车辆', '车辆年检'],
  'large-medical': ['住院费用', '手术费用', '体检套餐'],
  'large-emergency': ['应急垫付', '突发维修', '临时周转'],
  'housing-rent': ['交房租', '押金', '租房中介费'],
  'housing-loan': ['还房贷', '提前还款'],
  'housing-property': ['物业费', '车位管理费'],
  'housing-internet': ['宽带电视', '路由器设备'],
  'health-medicine': ['买药', '保健品', '常备药'],
  'health-clinic': ['挂号费', '检查费', '牙科', '眼科'],
  'education-course': ['课程学习', '考试报名', '培训费'],
  'education-book': ['买书', '电子书', '资料打印'],
  'other-temp': ['临时支出', '现金支出'],
  'other-unknown': ['未分类支出'],
  'salary-base': ['工资到账', '基本工资'],
  'salary-bonus': ['绩效奖金', '年终奖', '项目奖金'],
  'salary-subsidy': ['餐补', '交通补贴', '报销到账'],
  'part-time-job': ['兼职收入', '小时工收入'],
  'part-time-project': ['项目尾款', '稿费', '咨询费'],
  'part-time-service': ['服务酬劳', '劳务费'],
  'gift-redpacket': ['红包收入', '微信红包'],
  'gift-money': ['礼金收入', '份子钱回礼'],
  'gift-family': ['家人转账', '父母支持'],
  'finance-interest': ['利息到账', '银行收益'],
  'finance-investment': ['基金收益', '股票收益'],
  'finance-refund': ['退款', '返现', '押金退回'],
  'other-income-temp': ['临时收入'],
  'other-income-unknown': ['未分类收入'],
} as const;
