# Generated by Django 5.2.15 on 2026-06-10 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "收入"), ("expense", "支出")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="金额（分）")),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="备注"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="子分类"
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="时间")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="receipts/", verbose_name="图片"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "记账记录",
                "verbose_name_plural": "记账记录",
                "ordering": ["-date", "-time"],
            },
        ),
    ]
